### ISSUE TITLE
Tree recursion in `map` but not `filter`

### ISSUE THREAD

**Issue by andrewosh** [idyll-lang/idyll-component-children#1]
As of now, `filterChildren` will only apply the filter function to the top-level children, without recursing, but `mapChildren` will recurse to all child nodes in the given tree.

Should `filterChildren` be updated to filter deeper child nodes as well (i.e. the top level children might all pass the filter test, but a grandchild might fail -- keep all children, but remove the grandchild)?

**Comment by mathisonian** [comment]
I think this (not recursing) is the behavior we want for both, but its complicated a little by Idyll's internal modifications to the React tree.

Idyll basically reserves the right to wrap interactive components, such that if an author writes

```
<div>
   <CustomThing />
   <CustomThing />
</div>
```

it can be transformed into

```
<div>
   <Wrapper><CustomThing /></Wrapper>
   <Wrapper><CustomThing /></Wrapper>
</div>
```

for some internal uses of the runtime. This means that the utilities in this module need to be aware of and work around these wrappers. 

I believe you're right that there is a bug however, as it seems like https://github.com/idyll-lang/idyll-component-children/blob/master/index.js#L7-L9 would filter the children correctly but would remove the wrapper. 

Note that `mapChildren` won't recurse down the whole tree, just one level into `<Wrapper/>`'s

**Comment by mathisonian** [comment]
On second thought, I believe the current implementation of `filterChildren` is correct, but I'll add some tests. The current implementation should be fine as-is, unless there's a compelling reason for these things to act truly recursively.
